-- SQL para criar as tabelas da funcionalidade de Prioridades

-- Tabela de base de clientes
CREATE TABLE IF NOT EXISTS clientes_base (
    codigo_cliente TEXT PRIMARY KEY,
    regiao TEXT,
    numero TEXT,
    sigla TEXT,
    razao_social TEXT,
    vendedor TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE clientes_base DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_clientes_base_sigla ON clientes_base(sigla);
CREATE INDEX IF NOT EXISTS idx_clientes_base_razao ON clientes_base(razao_social);

-- Tabela de clientes prioritários
CREATE TABLE IF NOT EXISTS clientes_prioridade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cliente TEXT REFERENCES clientes_base(codigo_cliente) ON DELETE CASCADE,
    sigla TEXT,
    razao_social TEXT,
    vendedor TEXT,
    data_inclusao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(codigo_cliente)
);

ALTER TABLE clientes_prioridade DISABLE ROW LEVEL SECURITY;
